### ISSUE TITLE
Don't add -fno-strict-aliasing by default to C flags

### ISSUE THREAD

**Issue by rlsosborne** [xcore/xcommon#10]
module_xcommon/build/Makefile.common1 contains:

EXTRA_C_FLAGS += -fno-strict-aliasing

This forces the C compiler to be more conservative when optimizing. It seems wrong to do this globally - It should be the responsibility of apps that need the option to their own makefiles.

**Comment by ghost** [comment]
I'm not sure why this was in there in the first place. With the current compiler this does not make any difference so it is safe (and correct) to remove it.

I've already pushed the change for this.
