### ISSUE TITLE
Doesn't support parallel make (-jN)

### ISSUE THREAD

**Issue by rlsosborne** [xcore/xcommon#13]
If I build an application with xmake -j4 I get the warning:

xmake[1]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.

As a result I don't get any speedup with multiple processors.

If all the references to xmake are changed to $(MAKE) parallel builds work as expected. This speeds up the build of AVB from 48 seconds to 38 seconds on my dual core machine.

**Comment by ghost** [comment]
Fixed.
